### ISSUE TITLE
Simplify `github_release_link` workflow

### ISSUE THREAD

**Issue by alexesprit** [nocturlab/setup-vlang-action#23]
Instead of updating the reference to latest release manually, we could use an action. I found `Actions-R-Us/actions-tagger` which does this automatically.

An example of the workflow file using this action:
```yml
name: Update version reference
on:
  release:
    types: [published, edited]
jobs:
  update-ref:
    name: Update reference
    runs-on: ubuntu-latest
    steps:
    - uses: Actions-R-Us/actions-tagger@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
