### ISSUE TITLE
Doesn't download required compiler to build

### ISSUE THREAD

**Issue by ChildishGiant** [nocturlab/setup-vlang-action#39]
```
sh: 1: x86_64-w64-mingw32-gcc: not found
builder error: 
==================
C error. This should never happen.

If you were not working with C interop, please raise an issue on GitHub:

https://github.com/vlang/v/issues/new/choose

You can also use #help on Discord: https://discord.gg/vlang
```

**Comment by shiipou** [comment]
Can you show me your workflow file ?
Because a basic usage work for me on each arch (windows, macos, ubuntu).
See : https://github.com/nocturlab/setup-vlang-action/actions/runs/249445013/workflow

**Comment by ChildishGiant** [comment]
Here's the file: 
https://github.com/ChildishGiant/vlog/blob/master/.github/workflows/main.yml

```yml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup V environment
        uses: nocturlab/setup-vlang-action@v1.1.2
        with:
          v-version: master

      # Build nightly
      - name: Build vlog
        run: v -tcc -os windows build vlog.v |
             v -tcc -os linux build vlog.v 
```

**Comment by shiipou** [comment]
Ok, I see what wrong,
I need tu make the Action install `mingw-w64`
Until I fix it, you can install it by yourself using `apt install -y mingw-w64` or compiling V on windows directly by running the workflow with Matrix.

```yaml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup V environment
        uses: nocturlab/setup-vlang-action@v1.1.2
        with:
          v-version: master

      # Build nightly
      - name: Build vlog
        run: v -tcc -os windows build vlog.v |
             v -tcc -os linux build vlog.v 
```

**Comment by shiipou** [comment]
@ChildishGiant You can check my fork of your repository https://github.com/shiipou/vlog/actions/runs/257090986
The new workflow file I made generate 3 files (vlog-macos, vlog-linux, and vlog-windows)
![image](https://user-images.githubusercontent.com/38187238/93306471-33be0100-f800-11ea-858e-9b5b233c6a88.png)

**Comment by shiipou** [comment]
```yaml
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
    runs-on: ${{ matrix.os }}-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup V environment
        uses: nocturlab/setup-vlang-action@v1.1.2
        with:
          v-version: master

      # Build nightly
      - name: Build vlog
        run: v -o vlog-${{matrix.os}} vlog.v
             
      # Upload builds as artifacts
      - uses: actions/upload-artifact@v2
        with:
          name: builds
          path: |
            if [ "${{matrix.os}}" -eq "windows" ]; then
              vlog-${{matrix.os}}.exe
            else
              vlog-${{matrix.os}}
            fi
```
